In [57]:
import pandas as pd

df_pl = pd.read_csv("../data/raw/premier_league/premier_league_2023-2024.csv", encoding="latin1")

tables_ucl = pd.read_html("../data/raw/champions_league/ucl_2023-2024.xls")
df_ucl = tables_ucl[0]

print("Premier League :", df_pl.shape)
print("Champions League :", df_ucl.shape)

Premier League : (380, 106)
Champions League : (131, 13)

In [58]:
df_pl.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88

In [59]:
df_ucl.head()

,Round,Wk,Day,Date,Time,Home,Score,Away,Attendance,Venue,Referee,Match Report,Notes
0,Group stage,1.0,Tue,2023-09-19,18:45,Milan it,0â0,eng Newcastle,65695.0,Stadio Giuseppe Meazza,JosÃ© SÃ¡nchez,Match Report,NaN
1,Group stage,1.0,Tue,2023-09-19,18:45,Young Boys ch,1â3,de RB Leipzig,31500.0,Stadion Wankdorf,Enea Jorgji,Match Report,NaN
2,Group stage,1.0,Tue,2023-09-19,20:00 (21:00),Manchester City eng,3â1,rs Red Star,50204.0,Etihad Stadium,JoÃ£o Pinheiro,Match Report,NaN
3,Group stage,1.0,Tue,2023-09-19,21:00,PSG fr,2â0,de Dortmund,47379.0,Parc des Princes,JesÃºs Gil,Match Report,NaN
4,Group stage,1.0,Tue,2023-09-19,21:00,Lazio it,1â1,es AtlÃ©tico Madrid,46168.0,Stadio Olimpico,Slavko VinÄiÄ,Match Report,NaN

In [60]:
tables_ucl = pd.read_html("../data/raw/champions_league/ucl_2023-2024.xls", encoding="utf-8")
df_ucl = tables_ucl[0]
df_ucl.head()

,Round,Wk,Day,Date,Time,Home,Score,Away,Attendance,Venue,Referee,Match Report,Notes
0,Group stage,1.0,Tue,2023-09-19,18:45,Milan it,0–0,eng Newcastle,65695.0,Stadio Giuseppe Meazza,José Sánchez,Match Report,NaN
1,Group stage,1.0,Tue,2023-09-19,18:45,Young Boys ch,1–3,de RB Leipzig,31500.0,Stadion Wankdorf,Enea Jorgji,Match Report,NaN
2,Group stage,1.0,Tue,2023-09-19,20:00 (21:00),Manchester City eng,3–1,rs Red Star,50204.0,Etihad Stadium,João Pinheiro,Match Report,NaN
3,Group stage,1.0,Tue,2023-09-19,21:00,PSG fr,2–0,de Dortmund,47379.0,Parc des Princes,Jesús Gil,Match Report,NaN
4,Group stage,1.0,Tue,2023-09-19,21:00,Lazio it,1–1,es Atlético Madrid,46168.0,Stadio Olimpico,Slavko Vinčič,Match Report,NaN

In [61]:
# Nettoyage des noms d'équipes (suppression des codes pays)
df_ucl["Home"] = df_ucl["Home"].str.replace(r"\s+[a-z]{2,3}$", "", regex=True)
df_ucl["Away"] = df_ucl["Away"].str.replace(r"^[a-z]{2,3}\s+", "", regex=True)

df_ucl[["Home", "Away", "Score", "Round"]].head(10)

              Home             Away Score        Round
0            Milan        Newcastle   0–0  Group stage
1       Young Boys       RB Leipzig   1–3  Group stage
2  Manchester City         Red Star   3–1  Group stage
3              PSG         Dortmund   2–0  Group stage
4            Lazio  Atlético Madrid   1–1  Group stage
5        Feyenoord           Celtic   2–0  Group stage
6        Barcelona          Antwerp   5–0  Group stage
7      Shakhtar D.            Porto   1–3  Group stage
8      Real Madrid     Union Berlin   1–0  Group stage
9      Galatasaray    FC Copenhagen   2–2  Group stage

In [62]:
def load_ucl_season(filepath, season_label):
    """Charge et nettoie un fichier de résultats Champions League fbref."""
    tables = pd.read_html(filepath, encoding="utf-8")
    df = tables[0]
    
    df["Home"] = df["Home"].str.replace(r"\s+[a-z]{2,3}$", "", regex=True)
    df["Away"] = df["Away"].str.replace(r"^[a-z]{2,3}\s+", "", regex=True)
    
    df["season"] = season_label
    
    return df[["season", "Round", "Date", "Home", "Away", "Score", "Venue", "Referee"]]

# Test sur la saison qu'on vient de valider
df_test = load_ucl_season("../data/raw/champions_league/ucl_2023-2024.xls", "2023-2024")
df_test.head()

,season,Round,Date,Home,Away,Score,Venue,Referee
0,2023-2024,Group stage,2023-09-19,Milan,Newcastle,0–0,Stadio Giuseppe Meazza,José Sánchez
1,2023-2024,Group stage,2023-09-19,Young Boys,RB Leipzig,1–3,Stadion Wankdorf,Enea Jorgji
2,2023-2024,Group stage,2023-09-19,Manchester City,Red Star,3–1,Etihad Stadium,João Pinheiro
3,2023-2024,Group stage,2023-09-19,PSG,Dortmund,2–0,Parc des Princes,Jesús Gil
4,2023-2024,Group stage,2023-09-19,Lazio,Atlético Madrid,1–1,Stadio Olimpico,Slavko Vinčič

In [63]:
seasons_ucl = ["2016-2017", "2017-2018", "2018-2019", "2019-2020", "2020-2021",
               "2021-2022", "2022-2023", "2023-2024", "2024-2025", "2025-2026"]

all_ucl = []

for season in seasons_ucl:
    filepath = f"../data/raw/champions_league/ucl_{season}.xls"
    try:
        df_season = load_ucl_season(filepath, season)
        all_ucl.append(df_season)
        print(f"OK : {season} -> {df_season.shape[0]} matchs")
    except Exception as e:
        print(f"ERREUR sur {season} : {e}")

df_ucl_all = pd.concat(all_ucl, ignore_index=True)
print(f"\nTotal Champions League : {df_ucl_all.shape[0]} matchs sur {len(all_ucl)} saisons")
df_ucl_all.head()

OK : 2016-2017 -> 131 matchs
OK : 2017-2018 -> 131 matchs
OK : 2018-2019 -> 131 matchs
OK : 2019-2020 -> 125 matchs
OK : 2020-2021 -> 131 matchs
OK : 2021-2022 -> 131 matchs
OK : 2022-2023 -> 131 matchs
OK : 2023-2024 -> 131 matchs
OK : 2024-2025 -> 197 matchs
OK : 2025-2026 -> 197 matchs

Total Champions League : 1436 matchs sur 10 saisons

,season,Round,Date,Home,Away,Score,Venue,Referee
0,2016-2017,Group stage,2016-09-13,Benfica,Beşiktaş,1–1,Estádio do Sport Lisboa e Benfica,Milorad Mažić
1,2016-2017,Group stage,2016-09-13,Bayern Munich,Rostov,5–0,Allianz Arena,Anthony Taylor
2,2016-2017,Group stage,2016-09-13,PSG,Arsenal,1–1,Parc des Princes,Viktor Kassai
3,2016-2017,Group stage,2016-09-13,Barcelona,Celtic,7–0,Camp Nou,Ovidiu Hațegan
4,2016-2017,Group stage,2016-09-13,PSV,Atlético Madrid,0–1,Philips Stadion,Martin Atkinson

In [64]:
def load_league_season(filepath, league_name, season_label):
    """Charge et nettoie un fichier de résultats football-data.co.uk."""
    df = pd.read_csv(filepath, encoding="latin1")
    
    colonnes_utiles = ["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "HTHG", "HTAG"]
    df = df[colonnes_utiles].copy()
    
    df["league"] = league_name
    df["season"] = season_label
    
    return df

In [65]:
import glob
import os

pl_files = glob.glob("../data/raw/premier_league/*.csv")
all_pl = []

for filepath in pl_files:
    season = os.path.basename(filepath).replace("premier_league_", "").replace(".csv", "")
    try:
        df_season = load_league_season(filepath, "premier_league", season)
        all_pl.append(df_season)
        print(f"OK : {season} -> {df_season.shape[0]} matchs")
    except Exception as e:
        print(f"ERREUR sur {filepath} : {e}")

df_pl_all = pd.concat(all_pl, ignore_index=True)
print(f"\nTotal Premier League : {df_pl_all.shape[0]} matchs")
df_pl_all.head()

OK : 2020-2021 -> 380 matchs
OK : 2021-2022 -> 380 matchs
OK : 2019-2020 -> 380 matchs
OK : 2016-2017 -> 380 matchs
OK : 2018-2019 -> 380 matchs
OK : 2022-2023 -> 380 matchs
OK : 2023-2024 -> 380 matchs
OK : 2017-2018 -> 380 matchs
OK : 2024-2025 -> 380 matchs
OK : 2025-2026 -> 380 matchs

Total Premier League : 3800 matchs

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,league,season
0,12/09/2020,Fulham,Arsenal,0,3,A,0,1,premier_league,2020-2021
1,12/09/2020,Crystal Palace,Southampton,1,0,H,1,0,premier_league,2020-2021
2,12/09/2020,Liverpool,Leeds,4,3,H,3,2,premier_league,2020-2021
3,12/09/2020,West Ham,Newcastle,0,2,A,0,0,premier_league,2020-2021
4,13/09/2020,West Brom,Leicester,0,3,A,0,0,premier_league,2020-2021

In [66]:
def load_league_season(filepath, league_name, season_label):
    """Charge et nettoie un fichier de résultats football-data.co.uk."""
    df = pd.read_csv(filepath, encoding="latin1")
    
    colonnes_utiles = [
        "Date", "HomeTeam", "AwayTeam",
        "FTHG", "FTAG", "FTR",       # résultat final
        "HTHG", "HTAG", "HTR",       # résultat mi-temps
        "HS", "AS", "HST", "AST",    # tirs
        "HF", "AF",                  # fautes
        "HC", "AC",                  # corners
        "HY", "AY", "HR", "AR",      # cartons
        "B365H", "B365D", "B365A",   # cotes bookmaker
    ]
    
    # Certaines saisons anciennes n'ont pas toutes les colonnes (ex: cotes absentes) -> on filtre celles qui existent réellement
    colonnes_presentes = [c for c in colonnes_utiles if c in df.columns]
    df = df[colonnes_presentes].copy()
    
    df["league"] = league_name
    df["season"] = season_label
    
    return df

In [67]:
import glob
import os

pl_files = glob.glob("../data/raw/premier_league/*.csv")
all_pl = []

for filepath in pl_files:
    season = os.path.basename(filepath).replace("premier_league_", "").replace(".csv", "")
    try:
        df_season = load_league_season(filepath, "premier_league", season)
        all_pl.append(df_season)
        print(f"OK : {season} -> {df_season.shape[0]} matchs")
    except Exception as e:
        print(f"ERREUR sur {filepath} : {e}")

df_pl_all = pd.concat(all_pl, ignore_index=True)
print(f"\nTotal Premier League : {df_pl_all.shape[0]} matchs")
df_pl_all.head()

OK : 2020-2021 -> 380 matchs
OK : 2021-2022 -> 380 matchs
OK : 2019-2020 -> 380 matchs
OK : 2016-2017 -> 380 matchs
OK : 2018-2019 -> 380 matchs
OK : 2022-2023 -> 380 matchs
OK : 2023-2024 -> 380 matchs
OK : 2017-2018 -> 380 matchs
OK : 2024-2025 -> 380 matchs
OK : 2025-2026 -> 380 matchs

Total Premier League : 3800 matchs

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,...,AC,HY,AY,HR,AR,B365H,B365D,B365A,league,season
0,12/09/2020,Fulham,Arsenal,0,3,A,0,1,A,5,...,3,2,2,0,0,6.00,4.33,1.53,premier_league,2020-2021
1,12/09/2020,Crystal Palace,Southampton,1,0,H,1,0,H,5,...,3,2,1,0,0,3.10,3.25,2.37,premier_league,2020-2021
2,12/09/2020,Liverpool,Leeds,4,3,H,3,2,H,22,...,0,1,0,0,0,1.28,6.00,9.50,premier_league,2020-2021
3,12/09/2020,West Ham,Newcastle,0,2,A,0,0,D,15,...,7,2,2,0,0,2.15,3.40,3.40,premier_league,2020-2021
4,13/09/2020,West Brom,Leicester,0,3,A,0,0,D,7,...,5,1,1,0,0,3.80,3.60,1.95,premier_league,2020-2021

In [68]:
leagues = {
    "premier_league": "../data/raw/premier_league",
    "ligue_1": "../data/raw/ligue_1",
    "liga": "../data/raw/liga",
    "bundesliga": "../data/raw/bundesliga",
    "serie_a": "../data/raw/serie_a",
}

all_leagues = []

for league_name, folder in leagues.items():
    files = glob.glob(f"{folder}/*.csv")
    print(f"\n=== {league_name} ===")
    for filepath in files:
        season = os.path.basename(filepath).replace(f"{league_name}_", "").replace(".csv", "")
        try:
            df_season = load_league_season(filepath, league_name, season)
            all_leagues.append(df_season)
            print(f"OK : {season} -> {df_season.shape[0]} matchs")
        except Exception as e:
            print(f"ERREUR sur {filepath} : {e}")

df_leagues_all = pd.concat(all_leagues, ignore_index=True)
print(f"\nTotal 5 championnats : {df_leagues_all.shape[0]} matchs")

=== premier_league ===
OK : 2020-2021 -> 380 matchs
OK : 2021-2022 -> 380 matchs
OK : 2019-2020 -> 380 matchs
OK : 2016-2017 -> 380 matchs
OK : 2018-2019 -> 380 matchs
OK : 2022-2023 -> 380 matchs
OK : 2023-2024 -> 380 matchs
OK : 2017-2018 -> 380 matchs
OK : 2024-2025 -> 380 matchs
OK : 2025-2026 -> 380 matchs

=== ligue_1 ===
OK : 2020-2021 -> 380 matchs
OK : 2021-2022 -> 380 matchs
OK : 2019-2020 -> 279 matchs
OK : 2016-2017 -> 380 matchs
OK : 2018-2019 -> 380 matchs
OK : 2022-2023 -> 380 matchs
OK : 2023-2024 -> 306 matchs
OK : 2017-2018 -> 380 matchs
OK : 2024-2025 -> 306 matchs
OK : 2025-2026 -> 306 matchs

=== liga ===
OK : 2018-2019 -> 380 matchs
OK : 2016-2017 -> 380 matchs
OK : 2019-2020 -> 380 matchs
OK : 2021-2022 -> 380 matchs
OK : 2020-2021 -> 380 matchs
OK : 2025-2026 -> 380 matchs
OK : 2024-2025 -> 380 matchs
OK : 2017-2018 -> 380 matchs
OK : 2023-2024 -> 380 matchs
OK : 2022-2023 -> 380 matchs

=== bundesliga ===
OK : 2022-2023 -> 306 matchs
OK : 2017-2018 -> 306 matchs
OK : 2023-2024 -> 306 matchs
OK : 2025-2026 -> 306 matchs
OK : 2024-2025 -> 306 matchs
OK : 2021-2022 -> 306 matchs
OK : 2020-2021 -> 306 matchs
OK : 2016-2017 -> 306 matchs
OK : 2019-2020 -> 306 matchs
OK : 2018-2019 -> 306 matchs

=== serie_a ===
OK : 2019-2020 -> 380 matchs
OK : 2016-2017 -> 380 matchs
OK : 2018-2019 -> 380 matchs
OK : 2020-2021 -> 380 matchs
OK : 2021-2022 -> 380 matchs
OK : 2024-2025 -> 380 matchs
OK : 2025-2026 -> 380 matchs
OK : 2022-2023 -> 380 matchs
OK : 2023-2024 -> 380 matchs
OK : 2017-2018 -> 380 matchs

Total 5 championnats : 17937 matchs

In [69]:
rename_map = {
    "Date": "date",
    "HomeTeam": "home_team",
    "AwayTeam": "away_team",
    "FTHG": "full_time_home_goals",
    "FTAG": "full_time_away_goals",
    "FTR": "full_time_result",       # H = domicile gagne, D = nul, A = extérieur gagne
    "HTHG": "half_time_home_goals",
    "HTAG": "half_time_away_goals",
    "HTR": "half_time_result",
    "HS": "home_shots",
    "AS": "away_shots",
    "HST": "home_shots_on_target",
    "AST": "away_shots_on_target",
    "HF": "home_fouls",
    "AF": "away_fouls",
    "HC": "home_corners",
    "AC": "away_corners",
    "HY": "home_yellow_cards",
    "AY": "away_yellow_cards",
    "HR": "home_red_cards",
    "AR": "away_red_cards",
    "B365H": "odds_home_win",
    "B365D": "odds_draw",
    "B365A": "odds_away_win",
}

df_leagues_all = df_leagues_all.rename(columns=rename_map)
df_leagues_all.head()

,date,home_team,away_team,full_time_home_goals,full_time_away_goals,full_time_result,half_time_home_goals,half_time_away_goals,half_time_result,home_shots,...,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,odds_home_win,odds_draw,odds_away_win,league,season
0,12/09/2020,Fulham,Arsenal,0,3,A,0.0,1.0,A,5.0,...,3.0,2.0,2.0,0.0,0.0,6.00,4.33,1.53,premier_league,2020-2021
1,12/09/2020,Crystal Palace,Southampton,1,0,H,1.0,0.0,H,5.0,...,3.0,2.0,1.0,0.0,0.0,3.10,3.25,2.37,premier_league,2020-2021
2,12/09/2020,Liverpool,Leeds,4,3,H,3.0,2.0,H,22.0,...,0.0,1.0,0.0,0.0,0.0,1.28,6.00,9.50,premier_league,2020-2021
3,12/09/2020,West Ham,Newcastle,0,2,A,0.0,0.0,D,15.0,...,7.0,2.0,2.0,0.0,0.0,2.15,3.40,3.40,premier_league,2020-2021
4,13/09/2020,West Brom,Leicester,0,3,A,0.0,0.0,D,7.0,...,5.0,1.0,1.0,0.0,0.0,3.80,3.60,1.95,premier_league,2020-2021

In [70]:
# Combine chaque paire domicile/extérieur en une seule colonne texte "valeur_domicile-valeur_exterieur"

df_leagues_all["score"] = (
    df_leagues_all["full_time_home_goals"].astype(str) + "-" + df_leagues_all["full_time_away_goals"].astype(str)
)

df_leagues_all["half_time_score"] = (
    df_leagues_all["half_time_home_goals"].astype(str) + "-" + df_leagues_all["half_time_away_goals"].astype(str)
)

df_leagues_all["shots"] = (
    df_leagues_all["home_shots"].astype(str) + "-" + df_leagues_all["away_shots"].astype(str)
)

df_leagues_all["shots_on_target"] = (
    df_leagues_all["home_shots_on_target"].astype(str) + "-" + df_leagues_all["away_shots_on_target"].astype(str)
)

df_leagues_all["fouls"] = (
    df_leagues_all["home_fouls"].astype(str) + "-" + df_leagues_all["away_fouls"].astype(str)
)

df_leagues_all["corners"] = (
    df_leagues_all["home_corners"].astype(str) + "-" + df_leagues_all["away_corners"].astype(str)
)

df_leagues_all["yellow_cards"] = (
    df_leagues_all["home_yellow_cards"].astype(str) + "-" + df_leagues_all["away_yellow_cards"].astype(str)
)

df_leagues_all["red_cards"] = (
    df_leagues_all["home_red_cards"].astype(str) + "-" + df_leagues_all["away_red_cards"].astype(str)
)

df_leagues_all["odds"] = (
    df_leagues_all["odds_home_win"].astype(str) + "-" +
    df_leagues_all["odds_draw"].astype(str) + "-" +
    df_leagues_all["odds_away_win"].astype(str)
)

# On garde uniquement les colonnes finales, propres
colonnes_finales = [
    "date", "league", "season", "home_team", "away_team",
    "score", "half_time_score", "full_time_result", "half_time_result",
    "shots", "shots_on_target", "fouls", "corners", "yellow_cards", "red_cards", "odds"
]

df_leagues_clean = df_leagues_all[colonnes_finales].copy()
df_leagues_clean.head()

,date,league,season,home_team,away_team,score,half_time_score,full_time_result,half_time_result,shots,shots_on_target,fouls,corners,yellow_cards,red_cards,odds
0,12/09/2020,premier_league,2020-2021,Fulham,Arsenal,0-3,0.0-1.0,A,A,5.0-13.0,2.0-6.0,12.0-12.0,2.0-3.0,2.0-2.0,0.0-0.0,6.0-4.33-1.53
1,12/09/2020,premier_league,2020-2021,Crystal Palace,Southampton,1-0,1.0-0.0,H,H,5.0-9.0,3.0-5.0,14.0-11.0,7.0-3.0,2.0-1.0,0.0-0.0,3.1-3.25-2.37
2,12/09/2020,premier_league,2020-2021,Liverpool,Leeds,4-3,3.0-2.0,H,H,22.0-6.0,6.0-3.0,9.0-6.0,9.0-0.0,1.0-0.0,0.0-0.0,1.28-6.0-9.5
3,12/09/2020,premier_league,2020-2021,West Ham,Newcastle,0-2,0.0-0.0,A,D,15.0-15.0,3.0-2.0,13.0-7.0,8.0-7.0,2.0-2.0,0.0-0.0,2.15-3.4-3.4
4,13/09/2020,premier_league,2020-2021,West Brom,Leicester,0-3,0.0-0.0,A,D,7.0-13.0,1.0-7.0,12.0-9.0,2.0-5.0,1.0-1.0,0.0-0.0,3.8-3.6-1.95

In [71]:
# On retire les matchs sans score (pas encore joués)
avant = df_ucl_all.shape[0]
df_ucl_all = df_ucl_all.dropna(subset=["Score"])
df_ucl_all = df_ucl_all[df_ucl_all["Score"].str.contains("–", na=False)]
apres = df_ucl_all.shape[0]
print(f"Lignes retirées (matchs non joués) : {avant - apres}")

# Extraction robuste : on prend uniquement le score du temps réglementaire,
# on ignore ce qui est entre parenthèses (tirs au but)
scores_extracted = df_ucl_all["Score"].str.extract(r"(\d+)\s*(?:\(\d+\))?\s*–\s*(\d+)\s*(?:\(\d+\))?")

df_ucl_all["ucl_home_goals"] = scores_extracted[0].astype(int)
df_ucl_all["ucl_away_goals"] = scores_extracted[1].astype(int)

df_ucl_all.head()

Lignes retirées (matchs non joués) : 64

,season,Round,Date,Home,Away,Score,Venue,Referee,ucl_home_goals,ucl_away_goals
0,2016-2017,Group stage,2016-09-13,Benfica,Beşiktaş,1–1,Estádio do Sport Lisboa e Benfica,Milorad Mažić,1,1
1,2016-2017,Group stage,2016-09-13,Bayern Munich,Rostov,5–0,Allianz Arena,Anthony Taylor,5,0
2,2016-2017,Group stage,2016-09-13,PSG,Arsenal,1–1,Parc des Princes,Viktor Kassai,1,1
3,2016-2017,Group stage,2016-09-13,Barcelona,Celtic,7–0,Camp Nou,Ovidiu Hațegan,7,0
4,2016-2017,Group stage,2016-09-13,PSV,Atlético Madrid,0–1,Philips Stadion,Martin Atkinson,0,1

In [72]:
# Colonnes de stats détaillées disponibles pour les 5 championnats domestiques,
# absentes pour la Champions League (source fbref = buts uniquement)
stats_cols = [
    "half_time_home_goals", "half_time_away_goals", "full_time_result", "half_time_result",
    "home_shots", "away_shots", "home_shots_on_target", "away_shots_on_target",
    "home_fouls", "away_fouls", "home_corners", "away_corners",
    "home_yellow_cards", "away_yellow_cards", "home_red_cards", "away_red_cards",
    "odds_home_win", "odds_draw", "odds_away_win",
]

df_ucl_final = df_ucl_all.rename(columns={
    "Date": "date",
    "Home": "home_team",
    "Away": "away_team",
    "ucl_home_goals": "full_time_home_goals",
    "ucl_away_goals": "full_time_away_goals",
    "Round": "stage",
})
df_ucl_final["league"] = "champions_league"

# Pas de stats détaillées pour la Champions League -> colonnes vides plutôt que colonnes manquantes,
# pour garder un schéma commun avec les championnats domestiques
for col in stats_cols:
    df_ucl_final[col] = pd.NA

colonnes_communes = ["date", "league", "season", "home_team", "away_team",
                      "full_time_home_goals", "full_time_away_goals"] + stats_cols

df_ucl_final = df_ucl_final[colonnes_communes].copy()
df_leagues_final = df_leagues_all[colonnes_communes].copy()

# Formats de date différents selon la source -> conversion explicite avant fusion.
# Les championnats domestiques mélangent eux-mêmes deux formats selon la saison
# (ex: "12/09/2020" sur les saisons récentes, "13/08/16" sur les plus anciennes)
# -> format="mixed" pour laisser pandas détecter le bon format ligne par ligne.
df_leagues_final["date"] = pd.to_datetime(df_leagues_final["date"], format="mixed", dayfirst=True)
df_ucl_final["date"] = pd.to_datetime(df_ucl_final["date"], format="%Y-%m-%d")

df_ucl_final.head()

,date,league,season,home_team,away_team,full_time_home_goals,full_time_away_goals,half_time_home_goals,half_time_away_goals,full_time_result,...,away_fouls,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,odds_home_win,odds_draw,odds_away_win
0,2016-09-13,champions_league,2016-2017,Benfica,Beşiktaş,1,1,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2016-09-13,champions_league,2016-2017,Bayern Munich,Rostov,5,0,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,2016-09-13,champions_league,2016-2017,PSG,Arsenal,1,1,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,2016-09-13,champions_league,2016-2017,Barcelona,Celtic,7,0,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2016-09-13,champions_league,2016-2017,PSV,Atlético Madrid,0,1,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [73]:
df_all = pd.concat([df_leagues_final, df_ucl_final], ignore_index=True)
print(f"Total général : {df_all.shape[0]} matchs")
df_all["league"].value_counts()

Total général : 19309 matchs

/var/folders/g8/wl0c5j6d2m77r47k0zmrm6000000gn/T/ipykernel_84747/2562220505.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all = pd.concat([df_leagues_final, df_ucl_final], ignore_index=True)

league
premier_league      3800
liga                3800
serie_a             3800
ligue_1             3477
bundesliga          3060
champions_league    1372
Name: count, dtype: int64

## Sauvegarde de la base fusionnée brute

In [74]:
import os

os.makedirs("../data/processed", exist_ok=True)
df_all = df_all.sort_values("date").reset_index(drop=True)
df_all.to_csv("../data/processed/matches_all_raw.csv", index=False)
print(f"Sauvegardé : {df_all.shape[0]} lignes, {df_all.shape[1]} colonnes -> data/processed/matches_all_raw.csv")

Sauvegardé : 19309 lignes, 26 colonnes -> data/processed/matches_all_raw.csv

## Feature engineering : forme des équipes (rolling stats)

Objectif : pour chaque match, donner au modèle des indicateurs de forme de
chaque équipe **calculés uniquement à partir de ses matchs précédents**
(jamais le match en cours, jamais un match futur — sinon fuite de données :
le modèle "verrait" le résultat qu'il doit prédire).

Étapes :
1. Transformer `df_all` (1 ligne = 1 match) en `df_team_matches`
   (1 ligne = 1 équipe pour 1 match) — chaque match donne donc 2 lignes
   (perspective domicile + perspective extérieur).
2. Trier chronologiquement par équipe, et calculer des moyennes glissantes
   (buts, tirs, corners, points...) sur les 5 et 10 derniers matchs, en
   décalant d'un cran (`shift(1)`) pour exclure le match du jour.
3. Recoller ces stats de forme sur `df_all`, une fois côté équipe à domicile,
   une fois côté équipe à l'extérieur.

In [75]:
import numpy as np

def build_team_perspective(df):
    """Transforme la base 1-ligne-par-match en 1-ligne-par-équipe-par-match."""
    home = pd.DataFrame({
        "date": df["date"],
        "league": df["league"],
        "season": df["season"],
        "team": df["home_team"],
        "opponent": df["away_team"],
        "is_home": True,
        "goals_for": df["full_time_home_goals"],
        "goals_against": df["full_time_away_goals"],
        "shots_for": df["home_shots"],
        "shots_against": df["away_shots"],
        "shots_on_target_for": df["home_shots_on_target"],
        "shots_on_target_against": df["away_shots_on_target"],
        "corners_for": df["home_corners"],
        "corners_against": df["away_corners"],
        "fouls_for": df["home_fouls"],
        "fouls_against": df["away_fouls"],
    })
    away = pd.DataFrame({
        "date": df["date"],
        "league": df["league"],
        "season": df["season"],
        "team": df["away_team"],
        "opponent": df["home_team"],
        "is_home": False,
        "goals_for": df["full_time_away_goals"],
        "goals_against": df["full_time_home_goals"],
        "shots_for": df["away_shots"],
        "shots_against": df["home_shots"],
        "shots_on_target_for": df["away_shots_on_target"],
        "shots_on_target_against": df["home_shots_on_target"],
        "corners_for": df["away_corners"],
        "corners_against": df["home_corners"],
        "fouls_for": df["away_fouls"],
        "fouls_against": df["home_fouls"],
    })

    team_matches = pd.concat([home, away], ignore_index=True)

    # Résultat du point de vue de l'équipe -> points (victoire=3, nul=1, défaite=0)
    conditions = [
        team_matches["goals_for"] > team_matches["goals_against"],
        team_matches["goals_for"] == team_matches["goals_against"],
    ]
    team_matches["points"] = np.select(conditions, [3, 1], default=0)

    team_matches = team_matches.sort_values(["team", "date"]).reset_index(drop=True)
    return team_matches

df_team_matches = build_team_perspective(df_all)
print(f"{df_team_matches.shape[0]} lignes (2 x {df_all.shape[0]} matchs)")
df_team_matches.head()

38618 lignes (2 x 19309 matchs)

,date,league,season,team,opponent,is_home,goals_for,goals_against,shots_for,shots_against,shots_on_target_for,shots_on_target_against,corners_for,corners_against,fouls_for,fouls_against,points
0,2018-09-19,champions_league,2018-2019,AEK Athens,Ajax,False,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2018-10-02,champions_league,2018-2019,AEK Athens,Benfica,True,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2018-10-23,champions_league,2018-2019,AEK Athens,Bayern Munich,True,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2018-11-07,champions_league,2018-2019,AEK Athens,Bayern Munich,False,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2018-11-27,champions_league,2018-2019,AEK Athens,Ajax,True,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [76]:
def add_rolling_features(df, group_col="team", windows=(5, 10)):
    """
    Calcule des moyennes glissantes par équipe, en n'utilisant que les matchs
    STRICTEMENT antérieurs (shift(1)) pour éviter toute fuite de données.
    """
    df = df.sort_values([group_col, "date"]).copy()
    grouped = df.groupby(group_col, group_keys=False)

    stat_cols = [
        "goals_for", "goals_against", "shots_for", "shots_against",
        "shots_on_target_for", "shots_on_target_against",
        "corners_for", "corners_against", "fouls_for", "fouls_against", "points",
    ]

    for window in windows:
        for col in stat_cols:
            new_col = f"{col}_avg_last{window}"
            df[new_col] = grouped[col].transform(
                lambda s: s.shift(1).rolling(window, min_periods=1).mean()
            )

    # Nombre de matchs déjà joués avant celui-ci (utile pour filtrer les débuts
    # de saison / débuts d'historique, où la forme calculée est peu fiable)
    df["matches_played_before"] = grouped.cumcount()

    return df

df_team_matches = add_rolling_features(df_team_matches)
df_team_matches[
    ["team", "date", "goals_for", "goals_for_avg_last5", "points_avg_last5", "matches_played_before"]
].head(15)

,team,date,goals_for,goals_for_avg_last5,points_avg_last5,matches_played_before
0,AEK Athens,2018-09-19,0,NaN,NaN,0
1,AEK Athens,2018-10-02,2,0.000000,0.000000,1
2,AEK Athens,2018-10-23,0,1.000000,0.000000,2
3,AEK Athens,2018-11-07,0,0.666667,0.000000,3
4,AEK Athens,2018-11-27,0,0.500000,0.000000,4
5,AEK Athens,2018-12-12,0,0.400000,0.000000,5
6,APOEL FC,2017-09-13,0,NaN,NaN,0
7,APOEL FC,2017-09-26,0,0.000000,0.000000,1
8,APOEL FC,2017-10-17,1,0.000000,0.000000,2
9,APOEL FC,2017-11-01,1,0.333333,0.333333,3
10,APOEL FC,2017-11-21,0,0.500000,0.500000,4
11,APOEL FC,2017-12-06,0,0.400000,0.400000,5
12,Ajaccio,2022-08-05,1,NaN,NaN,0
13,Ajaccio,2022-08-14,0,1.000000,0.000000,1
14,Ajaccio,2022-08-21,1,0.500000,0.500000,2

### Forme spécifique domicile / extérieur

Les rolling stats ci-dessus mélangent, pour chaque équipe, ses matchs à
domicile et à l'extérieur dans une seule moyenne — on perd l'avantage du
terrain (une équipe peut être moyenne en général mais très forte chez elle).

On calcule donc les mêmes moyennes glissantes, mais séparément pour les
matchs à domicile et les matchs à l'extérieur de chaque équipe
(`groupby(["team", "is_home"])` au lieu de `groupby("team")`). Ainsi, côté
domicile du match, on utilisera la forme de l'équipe **spécifiquement à
domicile** ; côté extérieur, sa forme **spécifiquement à l'extérieur**.

In [77]:
def add_rolling_features_by_venue(df, windows=(5, 10)):
    """
    Comme add_rolling_features, mais la moyenne glissante est calculée
    séparément selon que l'équipe jouait à domicile ou à l'extérieur.
    Colonnes produites : "<stat>_avg_last<window>_venue".
    """
    df = df.sort_values(["team", "is_home", "date"]).copy()
    grouped = df.groupby(["team", "is_home"], group_keys=False)

    stat_cols = [
        "goals_for", "goals_against", "shots_for", "shots_against",
        "shots_on_target_for", "shots_on_target_against",
        "corners_for", "corners_against", "fouls_for", "fouls_against", "points",
    ]

    for window in windows:
        for col in stat_cols:
            new_col = f"{col}_avg_last{window}_venue"
            df[new_col] = grouped[col].transform(
                lambda s: s.shift(1).rolling(window, min_periods=1).mean()
            )

    return df

df_team_matches = add_rolling_features_by_venue(df_team_matches)
df_team_matches[
    ["team", "is_home", "date", "goals_for", "goals_for_avg_last5", "goals_for_avg_last5_venue"]
].head(15)

,team,is_home,date,goals_for,goals_for_avg_last5,goals_for_avg_last5_venue
0,AEK Athens,False,2018-09-19,0,NaN,NaN
3,AEK Athens,False,2018-11-07,0,0.666667,0.0
5,AEK Athens,False,2018-12-12,0,0.400000,0.0
1,AEK Athens,True,2018-10-02,2,0.000000,NaN
2,AEK Athens,True,2018-10-23,0,1.000000,2.0
4,AEK Athens,True,2018-11-27,0,0.500000,1.0
6,APOEL FC,False,2017-09-13,0,NaN,NaN
9,APOEL FC,False,2017-11-01,1,0.333333,0.0
11,APOEL FC,False,2017-12-06,0,0.400000,0.5
7,APOEL FC,True,2017-09-26,0,0.000000,NaN
8,APOEL FC,True,2017-10-17,1,0.000000,0.0
10,APOEL FC,True,2017-11-21,0,0.500000,0.5
12,Ajaccio,False,2022-08-05,1,NaN,NaN
14,Ajaccio,False,2022-08-21,1,0.500000,1.0
16,Ajaccio,False,2022-08-31,0,0.750000,1.0

### Repos entre matchs

Nombre de jours écoulés depuis le match précédent de l'équipe (toutes
compétitions confondues — championnat + Champions League). Capture la
fatigue / les enchaînements rapprochés (ex: match de Ligue des Champions en
semaine suivi d'un match de championnat le week-end).

In [78]:
def add_rest_days(df):
    """Jours depuis le match précédent de l'équipe, toutes compétitions confondues."""
    df = df.sort_values(["team", "date"]).copy()
    df["days_since_last_match"] = df.groupby("team")["date"].diff().dt.days
    return df

df_team_matches = add_rest_days(df_team_matches)
df_team_matches[["team", "date", "days_since_last_match"]].head(10)

         team       date  days_since_last_match
0  AEK Athens 2018-09-19                    NaN
1  AEK Athens 2018-10-02                   13.0
2  AEK Athens 2018-10-23                   21.0
3  AEK Athens 2018-11-07                   15.0
4  AEK Athens 2018-11-27                   20.0
5  AEK Athens 2018-12-12                   15.0
6    APOEL FC 2017-09-13                    NaN
7    APOEL FC 2017-09-26                   13.0
8    APOEL FC 2017-10-17                   21.0
9    APOEL FC 2017-11-01                   15.0

### Historique des confrontations directes (head-to-head)

Comment une équipe s'en sort habituellement **contre cet adversaire précis**
(certains matchs ont des dynamiques récurrentes indépendantes de la forme du
moment — rivalités, styles de jeu qui s'affrontent mal, etc.).

Les confrontations directes étant rares (2 fois par saison en championnat,
parfois aucune en Champions League d'une année sur l'autre), une fenêtre
glissante de 5 matchs n'aurait presque jamais assez de données. On utilise
donc une **moyenne expanding** (sur tout l'historique disponible, aussi
petit soit-il) plutôt qu'une moyenne glissante à fenêtre fixe.

In [79]:
def add_head_to_head_features(df):
    """
    Historique des confrontations directes entre une équipe et un adversaire
    précis : moyenne expanding (tout l'historique dispo) des points obtenus
    et de la différence de buts, toujours décalée d'un cran (shift(1)) pour
    exclure le match du jour.
    """
    df = df.sort_values(["team", "opponent", "date"]).copy()
    grouped = df.groupby(["team", "opponent"], group_keys=False)

    df["goal_diff"] = df["goals_for"] - df["goals_against"]

    df["h2h_points_avg"] = grouped["points"].transform(lambda s: s.shift(1).expanding().mean())
    df["h2h_goal_diff_avg"] = grouped["goal_diff"].transform(lambda s: s.shift(1).expanding().mean())
    df["h2h_matches_played"] = grouped.cumcount()

    return df

df_team_matches = add_head_to_head_features(df_team_matches)
df_team_matches[
    ["team", "opponent", "date", "points", "h2h_points_avg", "h2h_matches_played"]
].head(10)

,team,opponent,date,points,h2h_points_avg,h2h_matches_played
0,AEK Athens,Ajax,2018-09-19,0,NaN,0
4,AEK Athens,Ajax,2018-11-27,0,0.0,1
2,AEK Athens,Bayern Munich,2018-10-23,0,NaN,0
3,AEK Athens,Bayern Munich,2018-11-07,0,0.0,1
1,AEK Athens,Benfica,2018-10-02,0,NaN,0
5,AEK Athens,Benfica,2018-12-12,0,0.0,1
8,APOEL FC,Dortmund,2017-10-17,1,NaN,0
9,APOEL FC,Dortmund,2017-11-01,1,1.0,1
6,APOEL FC,Real Madrid,2017-09-13,0,NaN,0
10,APOEL FC,Real Madrid,2017-11-21,0,0.0,1

### Rating Elo par équipe

Un rating unique par équipe qui résume sa force globale, mis à jour après
**chaque** match (gain de rating contre une équipe plus forte que prévu,
perte contre une équipe plus faible que prévu). Contrairement aux moyennes
glissantes, il n'y a jamais de `NaN` : toute équipe démarre avec un rating
par défaut (1500) et il évolue ensuite match après match.

Le calcul est intrinsèquement **séquentiel** (le rating après le match N
dépend du rating après le match N-1) — on ne peut pas le vectoriser avec
`groupby`/`rolling` comme les autres features, on fait donc une boucle
`for` classique sur les matchs triés par date. On enregistre le rating
**avant** le match comme feature (donc sans fuite de données), puis on met
à jour les deux ratings avec le résultat réel.

In [ ]:
def compute_elo_ratings(df, k=20, initial_rating=1500, home_advantage=100):
    """
    Calcule un rating Elo par équipe, mis à jour après chaque match.
    k : vitesse d'ajustement du rating (plus haut = plus réactif, plus bruité).
    home_advantage : bonus (en points Elo) accordé à l'équipe à domicile
    avant de calculer sa probabilité de victoire attendue.
    """
    df = df.sort_values("date").reset_index(drop=True).copy()
    ratings = {}

    home_elo_before = []
    away_elo_before = []

    for _, row in df.iterrows():
        home, away = row["home_team"], row["away_team"]
        home_rating = ratings.get(home, initial_rating)
        away_rating = ratings.get(away, initial_rating)

        home_elo_before.append(home_rating)
        away_elo_before.append(away_rating)

        # Probabilité de victoire attendue (formule Elo standard)
        expected_home = 1 / (1 + 10 ** ((away_rating - (home_rating + home_advantage)) / 400))

        if row["full_time_home_goals"] > row["full_time_away_goals"]:
            actual_home = 1.0
        elif row["full_time_home_goals"] == row["full_time_away_goals"]:
            actual_home = 0.5
        else:
            actual_home = 0.0

        ratings[home] = home_rating + k * (actual_home - expected_home)
        ratings[away] = away_rating + k * ((1 - actual_home) - (1 - expected_home))

    df["home_elo_before"] = home_elo_before
    df["away_elo_before"] = away_elo_before

    return df

df_all = compute_elo_ratings(df_all)
df_all[["date", "home_team", "away_team", "home_elo_before", "away_elo_before"]].head(10)

### Recollage des features sur la base match par match

In [80]:
# On récupère uniquement les colonnes de features glissantes (pas les stats brutes du match)
feature_cols = [c for c in df_team_matches.columns if "_avg_last" in c] + [
    "matches_played_before", "days_since_last_match",
    "h2h_points_avg", "h2h_goal_diff_avg", "h2h_matches_played",
]

home_features = df_team_matches.loc[df_team_matches["is_home"], ["date", "team"] + feature_cols].copy()
home_features = home_features.rename(columns={"team": "home_team", **{c: f"home_{c}" for c in feature_cols}})

away_features = df_team_matches.loc[~df_team_matches["is_home"], ["date", "team"] + feature_cols].copy()
away_features = away_features.rename(columns={"team": "away_team", **{c: f"away_{c}" for c in feature_cols}})

df_features = df_all.merge(home_features, on=["date", "home_team"], how="left")
df_features = df_features.merge(away_features, on=["date", "away_team"], how="left")

print(f"{df_features.shape[0]} matchs, {df_features.shape[1]} colonnes")
df_features.filter(regex="date|home_team|away_team|goals_for_avg|points_avg|matches_played|days_since|h2h").head()

19309 matchs, 124 colonnes

,date,home_team,away_team,home_goals_for_avg_last5,home_points_avg_last5,home_goals_for_avg_last10,home_points_avg_last10,home_goals_for_avg_last5_venue,home_points_avg_last5_venue,home_goals_for_avg_last10_venue,...,away_points_avg_last10,away_goals_for_avg_last5_venue,away_points_avg_last5_venue,away_goals_for_avg_last10_venue,away_points_avg_last10_venue,away_matches_played_before,away_days_since_last_match,away_h2h_points_avg,away_h2h_goal_diff_avg,away_h2h_matches_played
0,2016-08-12,Bastia,Paris SG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
1,2016-08-12,Monaco,Guingamp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
2,2016-08-13,Crystal Palace,West Brom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
3,2016-08-13,Everton,Tottenham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0
4,2016-08-13,Hull,Leicester,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0

## Sauvegarde de la base avec features

In [81]:
df_features.to_csv("../data/processed/matches_features.csv", index=False)
print(f"Sauvegardé : {df_features.shape[0]} lignes, {df_features.shape[1]} colonnes -> data/processed/matches_features.csv")

Sauvegardé : 19309 lignes, 124 colonnes -> data/processed/matches_features.csv

## Suite du projet

La modélisation (split train/validation/test, entraînement, évaluation)
continue dans `02_modeling.ipynb`, à partir de `data/processed/matches_features.csv`
sauvegardé ci-dessus.